# Generated by Django 2.0.6 on 2018-06-06 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookTitles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_book', models.TextField(db_column='Title of Book')),
                ('book_type', models.CharField(choices=[('LI', 'List'), ('TE', 'Text'), ('TK', 'Textbook')], max_length=2, null=True)),
            ],
            options={
                'managed': True,
                'db_table': 'book_titles',
            },
        ),
        migrations.CreateModel(
            name='BookTitlesGreek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_book', models.TextField(db_column='Title of Book')),
                ('book_type', models.CharField(choices=[('LI', 'List'), ('TE', 'Text'), ('TK', 'Textbook')], max_length=2, null=True)),
            ],
            options={
                'managed': True,
                'db_table': 'book_titles_greek',
            },
        ),
        migrations.CreateModel(
            name='TextMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_for_humans', models.CharField(max_length=100)),
                ('name_for_computers', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=10)),
                ('local_def', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TextStructureGlossary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_name', models.CharField(max_length=100)),
                ('subsection_level', models.SmallIntegerField()),
                ('subsection_name', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TextStructureNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('text_name', models.CharField(blank=True, max_length=100)),
                ('subsection_level', models.SmallIntegerField()),
                ('subsection_id', models.CharField(max_length=6)),
                ('least_mindiv', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WordAppearencesGreek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_name', models.CharField(max_length=100)),
                ('text_name_for_computers', models.CharField(blank=True, max_length=100, null=True)),
                ('mindiv', models.SmallIntegerField()),
                ('appearance', models.CharField(max_length=100, null=True)),
                ('local_def', models.CharField(blank=True, max_length=1168, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WordAppearencesLatin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_name', models.CharField(max_length=100)),
                ('text_name_for_computers', models.CharField(blank=True, max_length=100, null=True)),
                ('mindiv', models.SmallIntegerField()),
                ('appearance', models.CharField(max_length=52, null=True)),
                ('local_def', models.CharField(blank=True, max_length=1168, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WordPropertyGreek',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('accented_lemma', models.CharField(blank=True, max_length=500, null=True)),
                ('logeion_lemma', models.CharField(blank=True, max_length=500, null=True)),
                ('search_lemma', models.CharField(blank=True, max_length=500, null=True)),
                ('display_lemma', models.CharField(blank=True, max_length=500, null=True)),
                ('english_definition', models.CharField(blank=True, max_length=500, null=True)),
                ('logeion_def', models.CharField(blank=True, max_length=500, null=True)),
                ('questions', models.CharField(blank=True, max_length=500, null=True)),
                ('decl', models.CharField(blank=True, max_length=4, null=True)),
                ('idiom', models.CharField(blank=True, max_length=1, null=True)),
                ('reg_adj_adv', models.CharField(blank=True, max_length=1, null=True)),
                ('proper', models.CharField(blank=True, max_length=1, null=True)),
                ('part_of_speech', models.CharField(blank=True, max_length=500, null=True)),
                ('exclude_1_0', models.IntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=500, null=True)),
                ('dcc_semantic_group', models.CharField(blank=True, max_length=500, null=True)),
                ('logeion_url', models.URLField(blank=True, null=True)),
                ('corpus_rank', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WordPropertyLatin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=60)),
                ('display_lemma', models.CharField(blank=True, max_length=84)),
                ('display_lemma_macronless', models.CharField(blank=True, max_length=83)),
                ('english_core', models.CharField(blank=True, max_length=155)),
                ('english_extended', models.CharField(blank=True, max_length=500)),
                ('lnm_definition', models.CharField(blank=True, max_length=74)),
                ('aeneid_definition', models.CharField(blank=True, max_length=1168)),
                ('catullus_definition', models.CharField(blank=True, max_length=245)),
                ('decl', models.CharField(blank=True, db_column='decl', max_length=1)),
                ('conj', models.CharField(blank=True, db_column='conj', max_length=1)),
                ('reg_adj_adv', models.CharField(blank=True, max_length=1)),
                ('proper', models.CharField(blank=True, max_length=1)),
                ('part_of_speech', models.CharField(blank=True, max_length=24)),
                ('dcc_frequency_group', models.CharField(blank=True, max_length=2)),
                ('dcc_semantic_group', models.CharField(blank=True, max_length=34)),
                ('logeion_url', models.URLField(blank=True, null=True)),
                ('corpus_rank', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='wordappearenceslatin',
            name='word',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='new_bridge.WordPropertyLatin'),
        ),
        migrations.AddField(
            model_name='wordappearencesgreek',
            name='word',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='new_bridge.WordPropertyGreek'),
        ),
    ]
