# Generated by Django 2.0.6 on 2018-07-30 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='wordpropertylatin',
            name='stopword',
            field=models.BooleanField(default=False)
        ),
        migrations.AddField(
            model_name='wordpropertygreek',
            name='stopword',
            field=models.BooleanField(default=False)
        ),
    ]
