# Generated by Django 2.0.6 on 2018-06-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemmatizer', '0013_auto_20180606_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formatlemmatizedtext',
            name='question',
            field=models.CharField(default='I + I = II', max_length=17),
        ),
        migrations.AlterField(
            model_name='lemmmatizer',
            name='question',
            field=models.CharField(default='I + I = II', max_length=15),
        ),
    ]
