# Generated by Django 2.0.6 on 2018-06-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemmatizer', '0018_auto_20180613_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formatlemmatizedtext',
            name='question',
            field=models.CharField(default='IV + VIII = ', max_length=17),
        ),
        migrations.AlterField(
            model_name='lemmmatizer',
            name='question',
            field=models.CharField(default='VIII - IV = ', max_length=15),
        ),
    ]
